import type { FieldMeta, ResourceMeta } from '@define/core'

import { toCamelCase, toKebabCase, toSafeIdentifier } from './naming.js'

const EOL = '\n'

export interface GeneratedFile {
  path: string
  code: string
}

export interface GenerateRepositoryArtifactsInput {
  resources: ResourceMeta[]
  schemaImportPath?: string
  dbImportPath?: string
}

export interface GenerateRepositoryArtifactsResult {
  files: GeneratedFile[]
}

const mapFieldType = (field: FieldMeta): string => {
  if (field.kind === 'string') {
    return 'string'
  }

  if (field.kind === 'int' || field.kind === 'id') {
    return 'number'
  }

  if (field.kind === 'datetime') {
    return 'Date'
  }

  if (field.kind === 'boolean') {
    return 'boolean'
  }

  const exhaustive: never = field.kind
  throw new Error(`Unsupported field kind: ${String(exhaustive)}`)
}

const renderType = (field: FieldMeta): string => {
  const base = mapFieldType(field)
  return field.nullable ? `${base} | null` : base
}

const isInsertOptional = (field: FieldMeta): boolean =>
  field.optional || field.autoIncrement || field.defaultValue !== undefined

const renderTypeFile = (resource: ResourceMeta): GeneratedFile => {
  const baseName = toKebabCase(resource.name)

  const rowFields = Object.entries(resource.fields)
    .map(([name, field]) => `  ${name}: ${renderType(field)}`)
    .join(EOL)

  const insertFields = Object.entries(resource.fields)
    .map(([name, field]) => {
      const optional = isInsertOptional(field) ? '?' : ''
      return `  ${name}${optional}: ${renderType(field)}`
    })
    .join(EOL)

  const updateFields = Object.entries(resource.fields)
    .filter(([, field]) => field.updatable)
    .map(([name, field]) => `  ${name}?: ${renderType(field)}`)
    .join(EOL)

  const code = [
    '// This file is generated by @define/cli. Do not edit manually.',
    '',
    `export interface ${resource.name}Row {`,
    rowFields,
    '}',
    '',
    `export interface ${resource.name}Insert {`,
    insertFields,
    '}',
    '',
    `export interface ${resource.name}Update {`,
    updateFields,
    '}',
    '',
  ].join(EOL)

  return {
    path: `${baseName}.types.ts`,
    code,
  }
}

const resolvePrimaryKey = (resource: ResourceMeta): string => {
  for (const [fieldName, field] of Object.entries(resource.fields)) {
    if (field.primary) {
      return fieldName
    }
  }

  if ('id' in resource.fields) {
    return 'id'
  }

  const [firstField] = Object.keys(resource.fields)

  if (!firstField) {
    throw new Error(`Resource ${resource.name} has no fields`)
  }

  return firstField
}

const renderRepoFile = (
  resource: ResourceMeta,
  schemaImportPath: string,
  dbImportPath: string,
): GeneratedFile => {
  const baseName = toKebabCase(resource.name)
  const tableIdentifier = toSafeIdentifier(resource.table)
  const primaryKeyName = resolvePrimaryKey(resource)
  const repositoryConst = `${resource.name}Repo`

  // Ensure import paths have .js extension for ESM module resolution
  const schemaImportWithExt = schemaImportPath.endsWith('.js') ? schemaImportPath : `${schemaImportPath}.js`
  const dbImportWithExt = dbImportPath.endsWith('.js') ? dbImportPath : `${dbImportPath}.js`

  const code = [
    '// This file is generated by @define/cli. Do not edit manually.',
    "import { eq } from 'drizzle-orm'",
    '',
    `import { db } from '${dbImportWithExt}'`,
    `import { ${tableIdentifier} } from '${schemaImportWithExt}'`,
    `import type { ${resource.name}Insert, ${resource.name}Row, ${resource.name}Update } from './${baseName}.types.js'`,
    '',
    `export const ${repositoryConst} = {`,
    `  insert: async (input: ${resource.name}Insert): Promise<${resource.name}Row> => {`,
    `    const [row] = await db.insert(${tableIdentifier}).values(input).returning()`,
    '    return row as unknown as ' + resource.name + 'Row',
    '  },',
    '',
    `  findById: async (id: unknown): Promise<${resource.name}Row | null> => {`,
    `    const [row] = await db.select().from(${tableIdentifier}).where(eq(${tableIdentifier}.${primaryKeyName}, id as ${resource.name}Row['${primaryKeyName}']))`,
    `    return (row as unknown as ${resource.name}Row | undefined) ?? null`,
    '  },',
    '',
    `  findMany: async (): Promise<${resource.name}Row[]> => {`,
    `    const rows = await db.select().from(${tableIdentifier})`,
    `    return rows as unknown as ${resource.name}Row[]`,
    '  },',
    '',
    `  updateById: async (id: unknown, patch: ${resource.name}Update): Promise<${resource.name}Row | null> => {`,
    `    const [row] = await db.update(${tableIdentifier}).set(patch).where(eq(${tableIdentifier}.${primaryKeyName}, id as ${resource.name}Row['${primaryKeyName}'])).returning()`,
    `    return (row as unknown as ${resource.name}Row | undefined) ?? null`,
    '  },',
    '}',
    '',
  ].join(EOL)

  return {
    path: `${baseName}.repo.ts`,
    code,
  }
}

const renderIndexFile = (resources: ResourceMeta[]): GeneratedFile => {
  const lines: string[] = ['// This file is generated by @define/cli. Do not edit manually.', '']

  for (const resource of resources) {
    const baseName = toKebabCase(resource.name)
    lines.push(`export * from './${baseName}.types.js'`)
    lines.push(`export * from './${baseName}.repo.js'`)
  }

  lines.push('')

  return {
    path: 'index.ts',
    code: lines.join(EOL),
  }
}

export const generateRepositoryArtifacts = ({
  resources,
  schemaImportPath = './drizzle-schema',
  dbImportPath = '../../src/db/client',
}: GenerateRepositoryArtifactsInput): GenerateRepositoryArtifactsResult => {
  const files: GeneratedFile[] = []

  for (const resource of resources) {
    files.push(renderTypeFile(resource))
    files.push(renderRepoFile(resource, schemaImportPath, dbImportPath))
  }

  files.push(renderIndexFile(resources))

  return { files }
}
