import type { FieldMeta, ResourceMeta } from '@define/core'

import type { ColumnBuilderName, GenerateDrizzleSchemaInput, GenerateDrizzleSchemaResult } from './types.js'
import { toSafeIdentifier } from './naming.js'

const EOL = '\n'

const reservedImportSet = new Set<string>(['pgTable'])

const serializeDefaultValue = (value: unknown): string => {
  if (value === undefined) {
    return ''
  }

  if (value === null) {
    return '.default(null)'
  }

  if (typeof value === 'string') {
    return `.default(${JSON.stringify(value)})`
  }

  if (typeof value === 'number' || typeof value === 'boolean') {
    return `.default(${String(value)})`
  }

  if (value instanceof Date) {
    return `.default(new Date(${JSON.stringify(value.toISOString())}))`
  }

  throw new Error(`Unsupported default value: ${String(value)}`)
}

const getColumnBuilder = (field: FieldMeta): ColumnBuilderName => {
  if (field.kind === 'id') {
    return field.autoIncrement ? 'serial' : 'integer'
  }

  if (field.kind === 'string') {
    return 'text'
  }

  if (field.kind === 'int') {
    return field.autoIncrement ? 'serial' : 'integer'
  }

  if (field.kind === 'datetime') {
    return 'timestamp'
  }

  if (field.kind === 'boolean') {
    return 'boolean'
  }

  const exhaustive: never = field.kind
  throw new Error(`Unsupported field kind: ${String(exhaustive)}`)
}

const buildColumnCode = (columnName: string, field: FieldMeta): string => {
  const builder = getColumnBuilder(field)
  reservedImportSet.add(builder)

  if (field.kind === 'datetime') {
    let datetimeColumn = `timestamp(${JSON.stringify(columnName)}, { mode: 'date' })`

    if (field.defaultValue === 'now') {
      datetimeColumn += '.defaultNow()'
    } else if (field.defaultValue !== undefined) {
      datetimeColumn += serializeDefaultValue(field.defaultValue)
    }

    if (!field.nullable) {
      datetimeColumn += '.notNull()'
    }

    if (field.primary) {
      datetimeColumn += '.primaryKey()'
    }

    if (field.unique) {
      datetimeColumn += '.unique()'
    }

    return datetimeColumn
  }

  let column = `${builder}(${JSON.stringify(columnName)})`

  if (field.defaultValue !== undefined) {
    column += serializeDefaultValue(field.defaultValue)
  }

  if (!field.nullable) {
    column += '.notNull()'
  }

  if (field.primary) {
    column += '.primaryKey()'
  }

  if (field.unique) {
    column += '.unique()'
  }

  return column
}

const buildTableCode = (resource: ResourceMeta): string => {
  const tableIdentifier = toSafeIdentifier(resource.table)
  const fieldEntries = Object.entries(resource.fields)

  const columns = fieldEntries
    .map(([fieldName, fieldMeta]) => {
      const columnCode = buildColumnCode(fieldName, fieldMeta)
      return `  ${fieldName}: ${columnCode},`
    })
    .join(EOL)

  return [
    `export const ${tableIdentifier} = pgTable(${JSON.stringify(resource.table)}, {`,
    columns,
    '})',
    '',
  ].join(EOL)
}

export const generateDrizzleSchema = ({
  resources,
}: GenerateDrizzleSchemaInput): GenerateDrizzleSchemaResult => {
  reservedImportSet.clear()
  reservedImportSet.add('pgTable')

  const tableBlocks = resources.map((resource) => buildTableCode(resource)).join(EOL)

  const imports = Array.from(reservedImportSet).sort().join(', ')

  const code = [
    '/* eslint-disable */',
    '// This file is generated by @define/cli. Do not edit manually.',
    `import { ${imports} } from 'drizzle-orm/pg-core'`,
    '',
    tableBlocks,
  ].join(EOL)

  return { code }
}
